### ISSUE TITLE
Bamboo-puppet-plugin is not compatible with bamboo 6.4

### ISSUE THREAD

**Issue by vlours** [croomes/bamboo-puppet-plugin#13]
Dear Simon,

The Bamboo add-ons "bamboo-puppet-plugin" is no longer compatible with Bamboo > 6.4 

Running it will generate Java Method Error:
```
simple	23-Mar-2018 10:35:13	Starting task 'Puppet Lint' of type 'org.croome.bamboo.plugins.bamboo-puppet-plugin:LintComponent'
simple	23-Mar-2018 10:35:13	Executing puppet-lint
error	23-Mar-2018 10:35:13	Error occurred while running Task '(4)' of type org.croome.bamboo.plugins.bamboo-puppet-plugin:LintComponent.
error	23-Mar-2018 10:35:13	java.lang.NoSuchMethodError: com.atlassian.bamboo.process.ProcessService.executeProcess(Lcom/atlassian/bamboo/task/TaskContext;Lcom/atlassian/bamboo/process/ExternalProcessBuilder;)Lcom/atlassian/utils/process/ExternalProcess;
error	23-Mar-2018 10:35:13		at org.croome.bamboo.plugins.puppet.tasks.lint.LintTask.execute(LintTask.java:144)
error	23-Mar-2018 10:35:13		at com.atlassian.bamboo.task.TaskExecutorImpl.lambda$executeTasks$2(TaskExecutorImpl.java:283)
error	23-Mar-2018 10:35:13		at com.atlassian.bamboo.task.TaskExecutorImpl.executeTaskWithPrePostActions(TaskExecutorImpl.java:224)
error	23-Mar-2018 10:35:13		at com.atlassian.bamboo.task.TaskExecutorImpl.executeTasks(TaskExecutorImpl.java:283)
error	23-Mar-2018 10:35:13		at com.atlassian.bamboo.task.TaskExecutorImpl.execute(TaskExecutorImpl.java:112)
error	23-Mar-2018 10:35:13		at com.atlassian.bamboo.build.pipeline.tasks.ExecuteBuildTask.call(ExecuteBuildTask.java:71)
error	23-Mar-2018 10:35:13		at com.atlassian.bamboo.v2.build.agent.DefaultBuildAgent.executeBuildPhase(DefaultBuildAgent.java:203)
error	23-Mar-2018 10:35:13		at com.atlassian.bamboo.v2.build.agent.DefaultBuildAgent.build(DefaultBuildAgent.java:175)
error	23-Mar-2018 10:35:13		at com.atlassian.bamboo.v2.build.agent.BuildAgentControllerImpl.lambda$waitAndPerformBuild$0(BuildAgentControllerImpl.java:122)
error	23-Mar-2018 10:35:13		at com.atlassian.bamboo.variable.CustomVariableContextImpl.withVariableSubstitutor(CustomVariableContextImpl.java:185)
error	23-Mar-2018 10:35:13		at com.atlassian.bamboo.v2.build.agent.BuildAgentControllerImpl.waitAndPerformBuild(BuildAgentControllerImpl.java:117)
error	23-Mar-2018 10:35:13		at com.atlassian.bamboo.v2.build.agent.DefaultBuildAgent$1.run(DefaultBuildAgent.java:126)
error	23-Mar-2018 10:35:13		at com.atlassian.bamboo.utils.BambooRunnables$1.run(BambooRunnables.java:48)
error	23-Mar-2018 10:35:13		at com.atlassian.bamboo.security.ImpersonationHelper.runWith(ImpersonationHelper.java:26)
error	23-Mar-2018 10:35:13		at com.atlassian.bamboo.security.ImpersonationHelper.runWithSystemAuthority(ImpersonationHelper.java:17)
error	23-Mar-2018 10:35:13		at com.atlassian.bamboo.security.ImpersonationHelper$1.run(ImpersonationHelper.java:41)
error	23-Mar-2018 10:35:13		at java.lang.Thread.run(Thread.java:748)
```

MarkSummers  has created a pull request which should solve this issue.
Can you please review it, and merge it if that fit in the code ?

Kind Regards,

**Comment by ricohomewood** [comment]
What's the status on this PR, Will it be merged soon as we are also running into this issue?

**Comment by khaefeli** [comment]
or could someone build the jar, that we could install it manually? ;)

**Comment by croomes** [comment]
Sorry for the delay with this.  I've merged the PR, but I don't have a java build environment as I'm not using this anymore.

If someone else is able to build & package, I can upload.  A co-maintainer would be great :)

**Comment by MarkSummers** [comment]
Sorry my GitHub notifications were being filtered into a blackhole.  I've fixed that now.  I also attached my build of the plugin.
[bamboo-puppet-plugin-1.0.2.jar.zip](https://github.com/croomes/bamboo-puppet-plugin/files/2090640/bamboo-puppet-plugin-1.0.2.jar.zip)

**Comment by khaefeli** [comment]
@MarkSummers I somehow always get an error during install. Don't find any logs - can someone else confirm this issue?

**Comment by MarkSummers** [comment]
@khaefeli Sorry for the slow reply.  I have compared MD5 hashes between the attached version and the version sitting in the plugins folder on our live Bamboo server, and they are the same.  Which version of Bamboo are you using?

**Comment by croomes** [comment]
I've just uploaded to the marketplace - sorry for the delay.  Please ask if you'd like to help maintain this.

https://marketplace.atlassian.com/apps/1211830/puppet-integration?hosting=server&tab=versions

**Comment by croomes** [comment]
Fixed by https://github.com/croomes/bamboo-puppet-plugin/pull/12

Thanks @vlours and @MarkSummers

**Comment by croomes** [comment]
Fixed by https://github.com/croomes/bamboo-puppet-plugin/pull/12

Thanks @vlours and @MarkSummers

**Comment by khaefeli** [comment]
@MarkSummers thank you for looking into the problem.
It's working now if I use the the addon from the marketplace.
