### ISSUE TITLE
Failing task since test cases were expected but none were found.

### ISSUE THREAD

**Issue by shawn-sterling** [croomes/bamboo-puppet-plugin#3]
Hi again. :) 

I am using a strategy of 1 git repo per module. The git repos are basically 'modulename' and each repo has a manifests dir with the *.pp files.

When I run the puppet-lint as is, I get the lint error: 'not in autoload module layout'. I could disable this error checking but it's actually a useful error that we run into a lot.

To work around this I setup the 'checkout directory' in the Source Code checkout task, to be the module directory name. This makes it so if I manually run the lint tool, I get no output and an exit code of 0. 

When I run from bamboo I get:

```
Beginning to execute external process for build 'Puppet Tests - asdf - Default Job #19 (PT-ASDF-JOB1-19)'\n ... running command line: \n/usr/bin/puppet-lint --with-filename --with-context .\n ... in: /bamboo/home/xml-data/build-dir/PT-ASDF-JOB1\n
simple	06-Apr-2014 16:00:19	Failing task since test cases were expected but none were found.
```

The directory structure:

```
[root@bamboo PT-ASDF-JOB1]# pwd
/bamboo/home/xml-data/build-dir/PT-ASDF-JOB1
[root@bamboo PT-ASDF-JOB1]# tree
.
└── usergroups
    └── manifests
        ├── custom_file.pp
        ├── setupgroups.pp
        ├── setup.pp
        ├── ssh_authorized_keys.pp
        └── users.pp

2 directories, 5 files
[root@bamboo PT-ASDF-JOB1]# cd usergroups/manifests/
[root@bamboo manifests]# puppet-lint *.pp
[root@bamboo manifests]# echo $?
0
```

Again this may be user error on my part. I have googled quite a bit on this error, and spent a fair amount of time on atlassian answers to no avail.

I think the extra directory from the 'checkout directory' is causing problems.

Have a good day.

-Shawn

**Comment by pugnacity** [comment]
is there any workaround for this?

**Comment by HT43-bqxFqB** [comment]
Can confirm that autoload does not seem to work currently. Furthermore there seems to be a need for at least 2 warning for a test to pass...

**Comment by aperto-armin** [comment]
+1

**Comment by samueljmarshall** [comment]
+1. This is a huge pain.

**Comment by liammonahan** [comment]
Version 1.0.1 from the marketplace should fix this issue.
