### ISSUE TITLE
Unable to find executable?

### ISSUE THREAD

**Issue by alexvirital** [croomes/bamboo-puppet-plugin#6]
Hey guys;

Followed the install instructions as directed, and yet we're seeing this error in the logs. It is able to run successfully, however it doesn't throw the lint output into the build - merely fails or passes without any syntax info. We're on bamboo 5.6.1.

Thanks for any help!

20-Oct-2014 15:48:33	Unable to find executable at puppet-lint. Will try to run it anyway.

**Comment by liammonahan** [comment]
Can you fully qualify the capability path and see what happens?
